### PR TITLE
Fixes #6 Trim potential whitespace around domains

### LINKED ISSUE #6: Error when domain env includes a space around domain name
e.g., `paasify.it,  www.paasify.it`

results in 

``` sh
2016/06/03 12:24:08 [INFO][paasify.it,  www.paasify.it] acme: Obtaining bundled SAN certificate
2016/06/03 12:24:08 acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: Invalid character in DNS name
```

Can we just auto strip this inside sabayon?

### PR DESCRIPTION
**Pull request by stefan-kolb**
Help users to avoid error due to whitespace  around `,` separator inside ENV variable.

### CODE REVIEW

File: cmd/sabayon/main.go [hunk 1]
```diff
@@ -21,6 +21,10 @@ func main() {
 	flag.Parse()
 
 	var domains = strings.Split(os.Getenv("ACME_DOMAIN"), ",")
+	// trim potential whitespace
+	for _, domain := range domains {
+		domain = strings.TrimSpace(domain)
```
Comment (dmathieu) [inline cmd/sabayon/main.go]: this will not work. `domain` is a local variable. So it won't update the array.
You need to do actually update the entry:

```
for i, domain := range domains {
  domains[i] = strings.TrimSpace(domain)
}
```

Comment (stefan-kolb) [inline cmd/sabayon/main.go]: omg sorry :smile:

Comment (dmathieu) [inline cmd/sabayon/main.go]: It's ok. You're the second person to write their first line of Go with this project. That's awesome :)

**Comment by dmathieu** [comment]
Thank you very much Stefan 🌷

**Comment by stefan-kolb** [comment]
Thanks for your patience :smile:
